Fix issue: Akka.Persistence fails to save snapshot when data is bigger than 65,535 bytes (#10)
* * Bugfix: Failed to save snapshot, Error: MySql.Data.MySqlClient.MySqlException: Data too long for column 'snapshot'

* + Release version increased

* Fix build script compilation error:
MySqlJournal.cs(26,63): error CS7036: There is no argument given that corresponds to the required formal parameter 'orderingColumnName' of 'QueryConfiguration.QueryConfiguration(string, string, string, string, string, string, string, string, string, string, string, TimeSpan)'

* Compilation fix: MySql.Data.MySqlClient.MySqlException: Field 'ordering' doesn't have a default value

* * Journal table structure aligned with Sqlite implementation (Ordering is primary key, PersistenceId is not PK anymore)

* * packages updated to latest versions

* * restore test password

* * code review fix: only Akka packages could be beta, all others are last stable release